---
output: github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  cache = FALSE,
  comment = "#>",
  message = FALSE,
  error = FALSE,
  warning = FALSE,
  fig.path = "README/README-",
  fig.width=7.3,
  fig.height=5,
  out.width = '100%'
)
```

## Description

`transitfeedr` is an R package for easily searching and getting GTFS feeds on [Transitfeeds](https://transitfeeds.com/) format.

## Installation

You can install this package from GitHub using the devtools package:

```
if (!require(devtools)) {
    install.packages('devtools')
}
devtools::install_github('r-gtfs/transitfeedr')
```

Example Usage
------------------

```{r readme-body}
library(dplyr)
library(transitfeedr)

# set the API key
# set_api_key() # uncomment to set api key

# get the feedlist dataframe and filter out NYC subway
feedlist_df <- get_feedlist() %>%
  filter(grepl('NYC Subway GTFS', t, ignore.case= TRUE))
```

Read the url with [tread](https://github.com/r-gtfs/tread)

```{r}
library(tread)
# import NYC gtfs feed by sending the url to `import_gtfs`
NYC <- import_gtfs(feedlist_df$url_d)
```
